name: npm audit fix

on:
  schedule:
    - cron: 0 0 * * * # Runs at 00:00 UTC every day

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ybiquitous/npm-audit-fix-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "npm-audit-fix"
          default_branch: "master"
          commit_title: "chore(deps): npm audit fix"
